version: '3.1'
services:
  db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "5432:5432"
  #    network_mode: bridge

  app:
    container_name: golang-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
#    network_mode: bridge