version: '3.1'
services:
  db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "5432:5432"
  app:
    container_name: golang-app
    env_file:
      - .env
    build: .
    ports:
      - "8080:8080"
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./build/golang-rest-api"]
    restart: "always"
    depends_on:
      - db
