# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: golang-restapi_app
      DOCKER_TAG: 1.0
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
#       docker-username:
#       docker-password:
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG

      - docker/push:
          digest-path: /tmp/digest.txt
          image: my_repo/orb-test
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  my-pipeline:
    jobs:
      - build-and-push:
#          requires:
#            - golang-test before build in here
          filters:
            branches:
              only:
                - master