# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  docker: circleci/docker@1.4.0
  dotenv: anilanar/dotenv@volatile

jobs:
  build-and-publish-docker-image:
    environment:
      DOCKER_IMAGE: truongvn/golang-restapi_app
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - dotenv/source:
          path: .env
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

#  deploy:
#    executor: docker/docker
#    steps:
#      - add_ssh_keys:
#          fingerprints:
#            - $SSH_KEY_FINGERPRINT
#      - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER './scripts/deploy.sh'
workflows:
  my-pipeline:
    jobs:
      - build-and-publish-docker-image:
          # requires:
          # - golang-test before build in here
          filters:
            branches:
              only:
                - master